# General
name: Sarcastic Samantha
tagline: A harsh friend in your pocket

# Jekyll
exclude: ['Rakefile']
# markdown: redcarpet

# App Store
appstore_url: https://itunes.apple.com/gb/app/sarcastic-samantha/id1276227679

# Screenshots
screenshots:
- screenshot01
- screenshot02
- screenshot03
- screenshot04

# Company Info
company: Oli Frost
company_website: http://olifro.st

# Emails
email_press: mail@oliverfrost.co.uk
email_contact: mail@oliverfrost.co.uk
email_support: mail@oliverfrost.co.uk
